<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd82172813c952d7f3536d0bbfdebe3ff
{
    public static $prefixLengthsPsr4 = array (
        'S' =>
        array (
            'ScssPhp\\ScssPhp\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ScssPhp\\ScssPhp\\' =>
        array (
            0 => __DIR__ . '/../scssphp/scssphp/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd82172813c952d7f3536d0bbfdebe3ff::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd82172813c952d7f3536d0bbfdebe3ff::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
